/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ShellExec */

#ifndef _Included_ShellExec
#define _Included_ShellExec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ShellExec
 * Method:    execute
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ShellExec_execute
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
